"use strict";
exports.__esModule = true;
var rl = require("readline-sync");
var choice = rl.question('Nhập lựa chọn: ');
console.log('-------Quản lí sinh viên--------');
console.log('1. Hiển thị thông tin sinh viên ');
console.log('2. Tạo thông tin sinh viên ');
console.log('3. Thêm thông tin sinh viên ');
console.log('4. Xóa thông tin sinh viên ');
console.log('5. Tìm kiếm thông tin sinh viên ');
